// Auto-generated by LibreLane
module sar_logic(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input Op,
  input Om,
  output[11:0] B,
  output[11:0] BN,
  output sign,
  output[11:0] D
);
endmodule
