/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 19.1.7 -fPIC -O3) */

module sar_logic(clk, rst, Op, Om, B, BN, sign, D);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  output [11:0] B;
  wire [11:0] B;
  output [11:0] BN;
  wire [11:0] BN;
  output [11:0] D;
  wire [11:0] D;
  input Om;
  wire Om;
  input Op;
  wire Op;
  input clk;
  wire clk;
  wire \dbit[0] ;
  wire \dbit[1] ;
  wire \dbit[2] ;
  wire \dbit[3] ;
  input rst;
  wire rst;
  output sign;
  wire sign;
  sg13g2_nor2b_1 _096_ (
    .A(Op),
    .B_N(Om),
    .Y(_050_)
  );
  sg13g2_nor2_1 _097_ (
    .A(\dbit[1] ),
    .B(\dbit[0] ),
    .Y(_051_)
  );
  sg13g2_or2_1 _098_ (
    .A(\dbit[1] ),
    .B(\dbit[0] ),
    .X(_052_)
  );
  sg13g2_nor2_1 _099_ (
    .A(\dbit[3] ),
    .B(\dbit[2] ),
    .Y(_053_)
  );
  sg13g2_nand3_1 _100_ (
    .A(_050_),
    .B(_051_),
    .C(_053_),
    .Y(_054_)
  );
  sg13g2_a21o_1 _101_ (
    .A1(BN[0]),
    .A2(_054_),
    .B1(rst),
    .X(_000_)
  );
  sg13g2_nor2b_1 _102_ (
    .A(\dbit[0] ),
    .B_N(\dbit[1] ),
    .Y(_055_)
  );
  sg13g2_nor2b_1 _103_ (
    .A(\dbit[2] ),
    .B_N(\dbit[3] ),
    .Y(_056_)
  );
  sg13g2_nand3_1 _104_ (
    .A(_050_),
    .B(_055_),
    .C(_056_),
    .Y(_057_)
  );
  sg13g2_a21o_1 _105_ (
    .A1(BN[10]),
    .A2(_057_),
    .B1(rst),
    .X(_001_)
  );
  sg13g2_nand4_1 _106_ (
    .A(\dbit[1] ),
    .B(\dbit[0] ),
    .C(_050_),
    .D(_056_),
    .Y(_058_)
  );
  sg13g2_a21o_1 _107_ (
    .A1(sign),
    .A2(_058_),
    .B1(rst),
    .X(_002_)
  );
  sg13g2_nor2b_1 _108_ (
    .A(\dbit[1] ),
    .B_N(\dbit[0] ),
    .Y(_059_)
  );
  sg13g2_nand3_1 _109_ (
    .A(_050_),
    .B(_053_),
    .C(_059_),
    .Y(_060_)
  );
  sg13g2_a21o_1 _110_ (
    .A1(BN[1]),
    .A2(_060_),
    .B1(rst),
    .X(_003_)
  );
  sg13g2_nand3_1 _111_ (
    .A(_050_),
    .B(_053_),
    .C(_055_),
    .Y(_061_)
  );
  sg13g2_a21o_1 _112_ (
    .A1(BN[2]),
    .A2(_061_),
    .B1(rst),
    .X(_004_)
  );
  sg13g2_nand4_1 _113_ (
    .A(\dbit[1] ),
    .B(\dbit[0] ),
    .C(_050_),
    .D(_053_),
    .Y(_062_)
  );
  sg13g2_a21o_1 _114_ (
    .A1(BN[3]),
    .A2(_062_),
    .B1(rst),
    .X(_005_)
  );
  sg13g2_nor2b_1 _115_ (
    .A(\dbit[3] ),
    .B_N(\dbit[2] ),
    .Y(_063_)
  );
  sg13g2_nand3_1 _116_ (
    .A(_050_),
    .B(_051_),
    .C(_063_),
    .Y(_064_)
  );
  sg13g2_a21o_1 _117_ (
    .A1(BN[4]),
    .A2(_064_),
    .B1(rst),
    .X(_006_)
  );
  sg13g2_nand3_1 _118_ (
    .A(_050_),
    .B(_059_),
    .C(_063_),
    .Y(_065_)
  );
  sg13g2_a21o_1 _119_ (
    .A1(BN[5]),
    .A2(_065_),
    .B1(rst),
    .X(_007_)
  );
  sg13g2_nand3_1 _120_ (
    .A(_050_),
    .B(_055_),
    .C(_063_),
    .Y(_066_)
  );
  sg13g2_a21o_1 _121_ (
    .A1(BN[6]),
    .A2(_066_),
    .B1(rst),
    .X(_008_)
  );
  sg13g2_nand4_1 _122_ (
    .A(\dbit[1] ),
    .B(\dbit[0] ),
    .C(_050_),
    .D(_063_),
    .Y(_067_)
  );
  sg13g2_a21o_1 _123_ (
    .A1(BN[7]),
    .A2(_067_),
    .B1(rst),
    .X(_009_)
  );
  sg13g2_nand3_1 _124_ (
    .A(_050_),
    .B(_051_),
    .C(_056_),
    .Y(_028_)
  );
  sg13g2_a21o_1 _125_ (
    .A1(BN[8]),
    .A2(_028_),
    .B1(rst),
    .X(_010_)
  );
  sg13g2_nand3_1 _126_ (
    .A(_050_),
    .B(_056_),
    .C(_059_),
    .Y(_029_)
  );
  sg13g2_a21o_1 _127_ (
    .A1(BN[9]),
    .A2(_029_),
    .B1(rst),
    .X(_011_)
  );
  sg13g2_nor2b_1 _128_ (
    .A(Om),
    .B_N(Op),
    .Y(_030_)
  );
  sg13g2_nand3_1 _129_ (
    .A(_051_),
    .B(_053_),
    .C(_030_),
    .Y(_031_)
  );
  sg13g2_a21o_1 _130_ (
    .A1(B[0]),
    .A2(_031_),
    .B1(rst),
    .X(_012_)
  );
  sg13g2_nand3_1 _131_ (
    .A(_055_),
    .B(_056_),
    .C(_030_),
    .Y(_032_)
  );
  sg13g2_a21o_1 _132_ (
    .A1(B[10]),
    .A2(_032_),
    .B1(rst),
    .X(_013_)
  );
  sg13g2_nand4_1 _133_ (
    .A(\dbit[1] ),
    .B(\dbit[0] ),
    .C(_056_),
    .D(_030_),
    .Y(_033_)
  );
  sg13g2_a21o_1 _134_ (
    .A1(B[11]),
    .A2(_033_),
    .B1(rst),
    .X(_014_)
  );
  sg13g2_nand3_1 _135_ (
    .A(_053_),
    .B(_059_),
    .C(_030_),
    .Y(_034_)
  );
  sg13g2_a21o_1 _136_ (
    .A1(B[1]),
    .A2(_034_),
    .B1(rst),
    .X(_015_)
  );
  sg13g2_nand3_1 _137_ (
    .A(_053_),
    .B(_055_),
    .C(_030_),
    .Y(_035_)
  );
  sg13g2_a21o_1 _138_ (
    .A1(B[2]),
    .A2(_035_),
    .B1(rst),
    .X(_016_)
  );
  sg13g2_nand4_1 _139_ (
    .A(\dbit[1] ),
    .B(\dbit[0] ),
    .C(_053_),
    .D(_030_),
    .Y(_036_)
  );
  sg13g2_a21o_1 _140_ (
    .A1(B[3]),
    .A2(_036_),
    .B1(rst),
    .X(_017_)
  );
  sg13g2_nand3_1 _141_ (
    .A(_051_),
    .B(_063_),
    .C(_030_),
    .Y(_037_)
  );
  sg13g2_a21o_1 _142_ (
    .A1(B[4]),
    .A2(_037_),
    .B1(rst),
    .X(_018_)
  );
  sg13g2_nand3_1 _143_ (
    .A(_059_),
    .B(_063_),
    .C(_030_),
    .Y(_038_)
  );
  sg13g2_a21o_1 _144_ (
    .A1(B[5]),
    .A2(_038_),
    .B1(rst),
    .X(_019_)
  );
  sg13g2_nand3_1 _145_ (
    .A(_055_),
    .B(_063_),
    .C(_030_),
    .Y(_039_)
  );
  sg13g2_a21o_1 _146_ (
    .A1(B[6]),
    .A2(_039_),
    .B1(rst),
    .X(_020_)
  );
  sg13g2_nand4_1 _147_ (
    .A(\dbit[1] ),
    .B(\dbit[0] ),
    .C(_063_),
    .D(_030_),
    .Y(_040_)
  );
  sg13g2_a21o_1 _148_ (
    .A1(B[7]),
    .A2(_040_),
    .B1(rst),
    .X(_021_)
  );
  sg13g2_nand3_1 _149_ (
    .A(_051_),
    .B(_056_),
    .C(_030_),
    .Y(_041_)
  );
  sg13g2_a21o_1 _150_ (
    .A1(B[8]),
    .A2(_041_),
    .B1(rst),
    .X(_022_)
  );
  sg13g2_nand3_1 _151_ (
    .A(_056_),
    .B(_059_),
    .C(_030_),
    .Y(_042_)
  );
  sg13g2_a21o_1 _152_ (
    .A1(B[9]),
    .A2(_042_),
    .B1(rst),
    .X(_023_)
  );
  sg13g2_or2_1 _153_ (
    .A(B[11]),
    .B(sign),
    .X(D[0])
  );
  sg13g2_mux2_1 _154_ (
    .A0(BN[9]),
    .A1(B[9]),
    .S(B[11]),
    .X(D[10])
  );
  sg13g2_mux2_1 _155_ (
    .A0(BN[10]),
    .A1(B[10]),
    .S(B[11]),
    .X(D[11])
  );
  sg13g2_mux2_1 _156_ (
    .A0(BN[0]),
    .A1(B[0]),
    .S(B[11]),
    .X(D[1])
  );
  sg13g2_mux2_1 _157_ (
    .A0(BN[1]),
    .A1(B[1]),
    .S(B[11]),
    .X(D[2])
  );
  sg13g2_mux2_1 _158_ (
    .A0(BN[2]),
    .A1(B[2]),
    .S(B[11]),
    .X(D[3])
  );
  sg13g2_mux2_1 _159_ (
    .A0(BN[3]),
    .A1(B[3]),
    .S(B[11]),
    .X(D[4])
  );
  sg13g2_mux2_1 _160_ (
    .A0(BN[4]),
    .A1(B[4]),
    .S(B[11]),
    .X(D[5])
  );
  sg13g2_mux2_1 _161_ (
    .A0(BN[5]),
    .A1(B[5]),
    .S(B[11]),
    .X(D[6])
  );
  sg13g2_mux2_1 _162_ (
    .A0(BN[6]),
    .A1(B[6]),
    .S(B[11]),
    .X(D[7])
  );
  sg13g2_mux2_1 _163_ (
    .A0(BN[7]),
    .A1(B[7]),
    .S(B[11]),
    .X(D[8])
  );
  sg13g2_mux2_1 _164_ (
    .A0(BN[8]),
    .A1(B[8]),
    .S(B[11]),
    .X(D[9])
  );
  sg13g2_xnor2_1 _165_ (
    .A(Op),
    .B(Om),
    .Y(_043_)
  );
  sg13g2_a21o_1 _166_ (
    .A1(_051_),
    .A2(_053_),
    .B1(_043_),
    .X(_044_)
  );
  sg13g2_a21oi_1 _167_ (
    .A1(\dbit[0] ),
    .A2(_043_),
    .B1(rst),
    .Y(_045_)
  );
  sg13g2_o21ai_1 _168_ (
    .A1(\dbit[0] ),
    .A2(_044_),
    .B1(_045_),
    .Y(_024_)
  );
  sg13g2_o21ai_1 _169_ (
    .A1(\dbit[0] ),
    .A2(_043_),
    .B1(\dbit[1] ),
    .Y(_046_)
  );
  sg13g2_or3_1 _170_ (
    .A(_052_),
    .B(_053_),
    .C(_043_),
    .X(_047_)
  );
  sg13g2_nand3b_1 _171_ (
    .A_N(rst),
    .B(_046_),
    .C(_047_),
    .Y(_025_)
  );
  sg13g2_nand3b_1 _172_ (
    .A_N(_043_),
    .B(_056_),
    .C(_051_),
    .Y(_048_)
  );
  sg13g2_o21ai_1 _173_ (
    .A1(_052_),
    .A2(_043_),
    .B1(\dbit[2] ),
    .Y(_049_)
  );
  sg13g2_a21oi_1 _174_ (
    .A1(_048_),
    .A2(_049_),
    .B1(rst),
    .Y(_026_)
  );
  sg13g2_a21o_1 _175_ (
    .A1(\dbit[3] ),
    .A2(_048_),
    .B1(rst),
    .X(_027_)
  );
  sg13g2_tiehi _176_ (
    .L_HI(_068_)
  );
  sg13g2_tiehi _177_ (
    .L_HI(_069_)
  );
  sg13g2_tiehi _178_ (
    .L_HI(_070_)
  );
  sg13g2_tiehi _179_ (
    .L_HI(_071_)
  );
  sg13g2_tiehi _180_ (
    .L_HI(_072_)
  );
  sg13g2_tiehi _181_ (
    .L_HI(_073_)
  );
  sg13g2_tiehi _182_ (
    .L_HI(_074_)
  );
  sg13g2_tiehi _183_ (
    .L_HI(_075_)
  );
  sg13g2_tiehi _184_ (
    .L_HI(_076_)
  );
  sg13g2_tiehi _185_ (
    .L_HI(_077_)
  );
  sg13g2_tiehi _186_ (
    .L_HI(_078_)
  );
  sg13g2_tiehi _187_ (
    .L_HI(_079_)
  );
  sg13g2_tiehi _188_ (
    .L_HI(_080_)
  );
  sg13g2_tiehi _189_ (
    .L_HI(_081_)
  );
  sg13g2_tiehi _190_ (
    .L_HI(_082_)
  );
  sg13g2_tiehi _191_ (
    .L_HI(_083_)
  );
  sg13g2_tiehi _192_ (
    .L_HI(_084_)
  );
  sg13g2_tiehi _193_ (
    .L_HI(_085_)
  );
  sg13g2_tiehi _194_ (
    .L_HI(_086_)
  );
  sg13g2_tiehi _195_ (
    .L_HI(_087_)
  );
  sg13g2_tiehi _196_ (
    .L_HI(_088_)
  );
  sg13g2_tiehi _197_ (
    .L_HI(_089_)
  );
  sg13g2_tiehi _198_ (
    .L_HI(_090_)
  );
  sg13g2_tiehi _199_ (
    .L_HI(_091_)
  );
  sg13g2_tiehi _200_ (
    .L_HI(_092_)
  );
  sg13g2_tiehi _201_ (
    .L_HI(_093_)
  );
  sg13g2_tiehi _202_ (
    .L_HI(_094_)
  );
  sg13g2_tiehi _203_ (
    .L_HI(_095_)
  );
  sg13g2_buf_1 _204_ (
    .A(sign),
    .X(BN[11])
  );
  sg13g2_dfrbpq_1 \BN[0]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_000_),
    .Q(BN[0]),
    .RESET_B(_071_)
  );
  sg13g2_dfrbpq_1 \BN[10]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_001_),
    .Q(BN[10]),
    .RESET_B(_094_)
  );
  sg13g2_dfrbpq_1 \BN[11]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_002_),
    .Q(sign),
    .RESET_B(_092_)
  );
  sg13g2_dfrbpq_1 \BN[1]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_003_),
    .Q(BN[1]),
    .RESET_B(_090_)
  );
  sg13g2_dfrbpq_1 \BN[2]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_004_),
    .Q(BN[2]),
    .RESET_B(_088_)
  );
  sg13g2_dfrbpq_1 \BN[3]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_005_),
    .Q(BN[3]),
    .RESET_B(_086_)
  );
  sg13g2_dfrbpq_1 \BN[4]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_006_),
    .Q(BN[4]),
    .RESET_B(_084_)
  );
  sg13g2_dfrbpq_1 \BN[5]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_007_),
    .Q(BN[5]),
    .RESET_B(_082_)
  );
  sg13g2_dfrbpq_1 \BN[6]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_008_),
    .Q(BN[6]),
    .RESET_B(_080_)
  );
  sg13g2_dfrbpq_1 \BN[7]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_009_),
    .Q(BN[7]),
    .RESET_B(_078_)
  );
  sg13g2_dfrbpq_1 \BN[8]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_010_),
    .Q(BN[8]),
    .RESET_B(_076_)
  );
  sg13g2_dfrbpq_1 \BN[9]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_011_),
    .Q(BN[9]),
    .RESET_B(_074_)
  );
  sg13g2_dfrbpq_1 \B[0]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_012_),
    .Q(B[0]),
    .RESET_B(_072_)
  );
  sg13g2_dfrbpq_1 \B[10]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_013_),
    .Q(B[10]),
    .RESET_B(_070_)
  );
  sg13g2_dfrbpq_1 \B[11]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_014_),
    .Q(B[11]),
    .RESET_B(_068_)
  );
  sg13g2_dfrbpq_1 \B[1]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_015_),
    .Q(B[1]),
    .RESET_B(_093_)
  );
  sg13g2_dfrbpq_1 \B[2]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_016_),
    .Q(B[2]),
    .RESET_B(_089_)
  );
  sg13g2_dfrbpq_1 \B[3]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_017_),
    .Q(B[3]),
    .RESET_B(_085_)
  );
  sg13g2_dfrbpq_1 \B[4]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_018_),
    .Q(B[4]),
    .RESET_B(_081_)
  );
  sg13g2_dfrbpq_1 \B[5]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_019_),
    .Q(B[5]),
    .RESET_B(_077_)
  );
  sg13g2_dfrbpq_1 \B[6]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_020_),
    .Q(B[6]),
    .RESET_B(_073_)
  );
  sg13g2_dfrbpq_1 \B[7]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_021_),
    .Q(B[7]),
    .RESET_B(_069_)
  );
  sg13g2_dfrbpq_1 \B[8]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_022_),
    .Q(B[8]),
    .RESET_B(_091_)
  );
  sg13g2_dfrbpq_1 \B[9]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_023_),
    .Q(B[9]),
    .RESET_B(_083_)
  );
  sg13g2_dfrbpq_1 \dbit[0]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_024_),
    .Q(\dbit[0] ),
    .RESET_B(_075_)
  );
  sg13g2_dfrbpq_1 \dbit[1]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_025_),
    .Q(\dbit[1] ),
    .RESET_B(_095_)
  );
  sg13g2_dfrbpq_1 \dbit[2]$_SDFFE_PP0P_  (
    .CLK(clk),
    .D(_026_),
    .Q(\dbit[2] ),
    .RESET_B(_079_)
  );
  sg13g2_dfrbpq_1 \dbit[3]$_SDFFE_PP1P_  (
    .CLK(clk),
    .D(_027_),
    .Q(\dbit[3] ),
    .RESET_B(_087_)
  );
endmodule
